### ISSUE TITLE
Terraform variables....

### ISSUE THREAD

**Issue by nfour14** [Xyrodileas/misp-k8s#2]
Hi! This is a great project - I plan to give it a test over the weekend. I do have a quick question, in the terraform init comamnd:

`terraform init -backend-config="key=misp" -backend-config="bucket=$(STATE_STORAGE_BUCKET)" -backend-config="region=$(STATE_STORAGE_REGION)"`

Where are the bucket and region variables coming from?

**Comment by jerem991** [comment]
Hi Jared!

It's coming from environment variables that were defined in our CICD pipeline.
Essentially STATE_STORAGE_BUCKET is the name of your AWS bucket, and STATE_STORAGE_REGION the region of were the bucket is hosted.

**Comment by nfour14** [comment]
Understood, Thanks!
